spring.application.name=fixit
spring.security.user.name=nikaru
spring.security.user.password=nikaru
spring.datasource.url=jdbc:postgresql://localhost:5432/fixit
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver